### ISSUE TITLE
(User Story): Festive visual theme

### ISSUE THREAD

**Issue by Will-WHyd** [Will-WHyd/Reindeer-Radar#4]
## Statement
As **Santa or his Helper**, I can **see a festive christmas themed design**, so that **I can get into the spirit of the season!**

# Acceptance Criteria
- Big christmas hero image - Clear and visible
- Santa & Sleigh for progress bar
- Landing page with festive design
- Sound effects 

## Tasks
- [ ]  Gather christmas themed stock images for use
- [ ]  Find Hero Image options for review 
- [ ]  Find sound effects 
- [ ] Gather them in Project's GDrive, then upload into project
